### PR TITLE
Major Update

### PR DESCRIPTION
**Pull request by natekspencer**
Updates login mechanism (no longer using open-id)
Adjustments to enums and creation of constants to follow some python best practices/naming conventions
Add common default properties (manufacturer, model, serial_number, software_version) to VivintDevice base class and adjusted inheriting classes where appropriate
Add reference to physical panel on AlarmPanel class
Add mac_address property as well as methods to retrieve the rtsp url (get_rtsp_url, get_direct_rtsp_url) to Camera and modify method names for getting thumbnails to remove implied "camera"
Added GarageDoor and relative capabilities and attributes
Add properties for equipment_code, equipment_type, and sensor_type to WirelessSensor
Other various adjustments across code to reflect updates to enums/constants, new method calls to the Vivint api, variable name corrections, etc.

### CODE REVIEW

**Comment by natekspencer** [comment]
I know this is a rather large update, so maybe it's taboo to create a pull request like this.

If you want too see how it works with Home Assistant, you can add my custom component from https://github.com/natekspencer/hacs-vivint and give it a go to see how it functions.

Let me know your thoughts on this!

**Comment by ovirs** [comment]
Thanks @natekspencer! This is awesome! I will take a look tonight and test it out.

**Comment by ovirs** [comment]
I have not tested it yet but this is looking great! Love the attention to details. Nice work @natekspencer !
Planning to give it a test tomorrow and assuming everything works ok will merge it.

**Comment by natekspencer** [comment]
@ovirs, it's a blessing and a curse, 😂. I definitely spend too much time on some things and rethink and refactor many times over as I go through the process. Hoping it works out well for your system! 🤞🏻

**Comment by ovirs** [comment]
Just tested it and it works perfectly so far. I'm going to merge this and if anything comes up we can address it later. Thank you for making all these changes!

**Pull request merged**
